"""
chp_units!(model::Model,cfg::Dict,tm::Dict,bdg::Dict,topo::Dict,sp::Dict,chp::Dict,
    abp::Dict)

Creates variables, expressions and constraints associated to CHP units

inputs:
model   name of core model
cfg     dictionary with configuration input data
tm      dictionary with time series data
bdg     dictionary with building data
topo    dictionary with topology of thermal connections
sp      dictionary with equipment selection data
chp     dictionary with CHP data
abp     dictionary with absorption chiller data

"""
function chp_units!(model::Model,cfg::Dict,tm::Dict,bdg::Dict,topo::Dict,sp::Dict,
    chp::Dict,abp::Dict)

    # energy --electricity-- generated by CHP [0,1]
    @variable(model, 1 >= vCHP_q[t=1:tm["P"],c=1:chp["N"]] >= 0)
    # commitment of CHP along simulation {0,1}
    @variable(model, bCHP_q[t=1:tm["P"],c=1:chp["N"]], Bin)
    # investment in CHP at investment window {0,1}
    @variable(model, bCHPty[i=1:cfg["IT"],c=1:chp["N"]], Bin)
    # existing CHP along simulation {0,1}
    @variable(model, bCHP_u[t=1:tm["P"],c=1:chp["N"]], Bin)

    # define bounds of binary investment variable
    set_upper_bound.(bCHPty,0)
    for c in findall(sp["CHP0"].!="0")
        # fix already installed CHP units
        for u=1:sp["CHPz0"][c]
            set_upper_bound.(bCHPty[1,chp["ty"].==string(sp["CHP0"][c],'-',u)],1)
            set_lower_bound.(bCHPty[1,chp["ty"].==string(sp["CHP0"][c],'-',u)],1)
        end
        # release potential installed CHP units
        if sp["CHPyn"][c] == "YES"
            for u=(sp["CHPz0"][c]+1):bdg["Bchp"]
                set_upper_bound.(bCHPty[:,chp["ty"].==string(sp["CHP0"][c],'-',u)],1)
            end
        end
    end

    # correct maximum capacity for non-existing or disabled CHP units
    chp["mx_eff"] = copy(chp["mx"])
    chp["mx_eff"][iszero.(upper_bound.(bCHPty[1,:]))] .= 0

    # energy --electricity-- generated by CHP [kWh]
    @expression(model, vCHP_Q[t=1:tm["P"],c=1:chp["N"]], tm["TM"][t]*chp["mx_eff"][c]*vCHP_q[t,c])
    # energy --heating-- generated per link by CHP to building [kWh]
    @expression(model, vCHP_HT[t=1:tm["P"],c=1:chp["N"]; (!iszero).(topo["chp_bdg"][c,1])],
        tm["TM"][t] * chp["mx_eff"][c]*topo["chp_bdg"][c,1]*model[:vCHPbdg][t,c,1])
    # energy --hot water-- generated per link by CHP [kWh]
    @expression(model, vCHP_HW[t=1:tm["P"],c=1:chp["N"]; (!iszero).(topo["chp_bdg"][c,2])],
        tm["TM"][t] * chp["mx_eff"][c]*topo["chp_bdg"][c,2]*model[:vCHPbdg][t,c,2])

    # gaseous fuel purchased by CHP units [kWh]
    if any(chp["fuel"].=="G")
        @expression(model, vCHP_G[t=1:tm["P"]],
            sum(vCHP_Q[t,c]/chp["fcf"][c] for c=1:chp["N"]
                if chp["mx_eff"][c]>0 && chp["h2p"][c]>0 && chp["fuel"][c]=="G" && chp["fcf"][c]>0) +
            sum(vCHP_HT[t,c]/chp["fcf"][c] for c=1:chp["N"]
                if chp["mx_eff"][c]>0 && chp["h2p"][c]==0 && chp["fuel"][c]=="G" && topo["chp_bdg"][c,1]>0 && chp["fcf"][c]>0) +
            sum(vCHP_HW[t,c]/chp["fcf"][c] for c=1:chp["N"]
                if chp["mx_eff"][c]>0 && chp["h2p"][c]==0 && chp["fuel"][c]=="G" && topo["chp_bdg"][c,2]>0 && chp["fcf"][c]>0))
    else
        @variable(model, vCHP_G[t=1:tm["P"]] == 0)
    end

    # liquid fuel purchased by CHP [kWh]
    if any(chp["fuel"].=="L")
        @expression(model, vCHP_L[t=1:tm["P"]],
            sum(vCHP_Q[t,c]/chp["fcf"][c] for c=1:chp["N"]
                if chp["mx_eff"][c]>0 && chp["h2p"][c]>0 && chp["fuel"][c]=="L" && chp["fcf"][c]>0) +
            sum(vCHP_HT[t,c]/chp["fcf"][c] for c=1:chp["N"]
                if chp["mx_eff"][c]>0 && chp["h2p"][c]==0 && chp["fuel"][c]=="L" && topo["chp_bdg"][c,1]>0 && chp["fcf"][c]>0) +
            sum(vCHP_HW[t,c]/chp["fcf"][c] for c=1:chp["N"]
                if chp["mx_eff"][c]>0 && chp["h2p"][c]==0 && chp["fuel"][c]=="L" && topo["chp_bdg"][c,2]>0 && chp["fcf"][c]>0))
    else
        @variable(model, vCHP_L[t=1:tm["P"]] == 0)
    end

    # maximum available space for CHP units {0,Bchp}
    @constraint(model, eCHPbdg,
        sum(bCHPty[i,c] for i=1:cfg["IT"],c=1:chp["N"] if chp["mx_eff"][c]>0) <= bdg["Bchp"])
    # only one investment per time window for CHP units {0,1}
    @constraint(model, eCHPw[c=1:chp["N"]; chp["mx_eff"][c]>0],
        sum(bCHPty[i,c] for i=1:cfg["IT"]) <= 1)
    # maximum electricity provided by CHP [0,1]
    @constraint(model, eCHPmx[t=1:tm["P"],c=1:chp["N"]; chp["mx_eff"][c]>0],
        vCHP_q[t,c] <= bCHP_q[t,c])
    # minimum electricity provided by CHP [0,1]
    @constraint(model, eCHPmn[t=1:tm["P"],c=1:chp["N"]; chp["mx_eff"][c]>0 && chp["mn"][c]>0],
    	vCHP_q[t,c] >= chp["mn"][c]*bCHP_q[t,c])
    # allowed commitment of CHP unit when existing {0,1}
    @constraint(model, eCHPu[t=1:tm["P"],c=1:chp["N"]; chp["mx_eff"][c]>0],
        bCHP_q[t,c] <= bCHP_u[t,c])
    # investment in CHP unit {0,1}
    for i1=1:cfg["IT"]
    	 @constraint(model, eCHPb[t=tm["IW"][i1]:tm["P"],c=1:chp["N"]; chp["mx_eff"][c]>0],
    		bCHP_u[t,c] == sum(bCHPty[i2,c] for i2=1:i1))
    end
    # disable electricity generation for boilers and furnaces
    @constraint(model, eCHPq0[t=1:tm["P"],c=1:chp["N"]; chp["h2p"][c]==0], vCHP_q[t,c] <= 0)
    # maximum heat provided by CHP [0,h2p]
    @constraint(model, eCHPht[t=1:tm["P"],c=1:chp["N"]; chp["mx_eff"][c]>0 && chp["h2p"][c]>0],
        sum(model[:vCHPbdg][t,c,l] for l=1:2 if topo["chp_bdg"][c,l]>0) +
        sum(model[:vCHPabp][t,c,a] for a=1:abp["N"] if topo["chp_abp"][c,a]>0) <= chp["h2p"][c]*vCHP_q[t,c])
    # maximum heat provided by CHP [0,1] - boilers
    @constraint(model, eCHPht0[t=1:tm["P"],c=1:chp["N"]; chp["mx_eff"][c]>0 && chp["h2p"][c]==0],
        sum(model[:vCHPbdg][t,c,l] for l=1:2 if topo["chp_bdg"][c,l]>0) +
        sum(model[:vCHPabp][t,c,a] for a=1:abp["N"] if topo["chp_abp"][c,a]>0) <= bCHP_u[t,c])

end