"""
pv_panels!(model::Model,cfg::Dict,tm::Dict,bdg::Dict,sp::Dict,pv::Dict)

Creates variables, expressions and constraints associated to PV panels

inputs:
model   name of core model
cfg     dictionary with configuration input data
tm      dictionary with time series data
bdg     dictionary with building data
sp      dictionary with equipment selection data
pv      dictionary with PV data

"""
function pv_panels!(model::Model,cfg::Dict,tm::Dict,bdg::Dict,sp::Dict,pv::Dict)

    # electricity generation by PV panel [kWh]
    @variable(model,
        pv["pv_cf"][t,v].*pv["zmx"][v].*pv["eff"][v].*pv["mx"][v] >= vPV_Q[t=1:tm["P"],v=1:pv["N"]] >= 0)
    # investment in total # PV panels [0,z]
    @variable(model, 0 >= zPV[i=1:cfg["IT"],v=1:pv["N"]] >= 0, Int)

    pv["zmx0"] = zeros(Int16, pv["N"])    # maximum number of potential existing PV panels
    for v in findall(sp["PV0"].!="0")
        # fix already installed PV panels
        if sp["PVyn"][v] == "NO"
            set_upper_bound.(zPV[1,pv["ty"].==sp["PV0"][v]],sp["PVz0"][v])
            set_lower_bound.(zPV[1,pv["ty"].==sp["PV0"][v]],sp["PVz0"][v])
            pv["zmx0"][pv["ty"].==sp["PV0"][v]] .= sp["PVz0"][v]
        # set bounds of potential PV panels
        elseif sp["PVyn"][v] == "YES"
            set_upper_bound.(zPV[:,pv["ty"].==sp["PV0"][v]],pv["zmx"][pv["ty"].==sp["PV0"][v]])
            set_lower_bound.(zPV[1,pv["ty"].==sp["PV0"][v]],sp["PVz0"][v])
            pv["zmx0"][pv["ty"].==sp["PV0"][v]] .= pv["zmx"][pv["ty"].==sp["PV0"][v]]
        end
    end

    # maximum available surface for PV panels [m2]
    @constraint(model, ePVbdg,
        sum(pv["ar"][v]*zPV[i,v] for i=1:cfg["IT"], v=1:pv["N"] if pv["zmx0"][v]>0) <= bdg["Bpv"])
    # maximum electricity generated by PV panels [kWh]
    for i1=1:cfg["IT"]
        tlast = i1 < cfg["IT"] ? tm["IW"][i1+1]-1 : tm["P"]
        @constraint(model, [t=tm["IW"][i1]:tlast,v=1:pv["N"]; pv["zmx0"][v]>0],
            vPV_Q[t,v] <= tm["TM"][t]*pv["pv_cf"][t,v]*(sum(zPV[i2,v] for i2=1:i1))*pv["eff"][v].*pv["mx"][v])
    end

end
