"""
wind_turbines!(model::Model,cfg::Dict,tm::Dict,bdg::Dict,sp::Dict,wind::Dict)

Creates variables, expressions and constraints associated to wind turbines

inputs:
model   name of core model
cfg     dictionary with configuration input data
tm      dictionary with time series data
bdg     dictionary with building data
sp      dictionary with equipment selection data
wind    dictionary with wind turbines data

"""
function wind_turbines!(model::Model,cfg::Dict,tm::Dict,bdg::Dict,sp::Dict,wind::Dict)

    # electricity generation by wind turbine [kWh]
    @variable(model, bdg["Bwind"] >= vWINDq[t=1:tm["P"],d=1:wind["N"]] >= 0)
    # investment in total # WIND turbines {0,z}
    @variable(model, 0 >= zWIND[i=1:cfg["IT"],d=1:wind["N"]] >= 0, Int)

    wind["zmx0"] = zeros(Int16, wind["N"])      # maximum number of potential existing wind turbines
    for d in findall(sp["WIND0"].!="0")
        # fix already installed wind turbines
        if sp["WINDyn"][d] == "NO"
            set_upper_bound.(zWIND[1,wind["ty"].==sp["WIND0"][d]],sp["WINDz0"][d])
            set_lower_bound.(zWIND[1,wind["ty"].==sp["WIND0"][d]],sp["WINDz0"][d])
            wind["zmx0"][wind["ty"].==sp["WIND0"][d]] .= sp["WINDz0"][d]
        # set bounds of potential wind turbines
        elseif sp["WINDyn"][d] == "YES"
            set_upper_bound.(zWIND[:,wind["ty"].==sp["WIND0"][d]],bdg["Bwind"])
            set_lower_bound.(zWIND[1,wind["ty"].==sp["WIND0"][d]],sp["WINDz0"][d])
            wind["zmx0"][wind["ty"].==sp["WIND0"][d]] .= bdg["Bwind"]
        end
    end

    # electricity generated by wind turbine [kWh]
    @expression(model, vWIND_Q[t=1:tm["P"],d=1:wind["N"]], tm["TM"][t]*wind["Q"][t,d]*vWINDq[t,d])

    # maximum available space for WIND turbines {0,z}
    @constraint(model, eWINDbdg, sum(zWIND[i,d] for i=1:cfg["IT"],d=1:wind["N"]) <= bdg["Bwind"])
    # maximum electricity generated by WIND turbines [kWh]
    for i1=1:cfg["IT"]
        tlast = i1 < cfg["IT"] ? tm["IW"][i1+1]-1 : tm["P"]
        @constraint(model, [t=tm["IW"][i1]:tlast,d=1:wind["N"]; wind["zmx0"][d]>0],
            vWINDq[t,d] <= sum(zWIND[i2,d] for i2=1:i1))
    end

end
